#!/usr/bin/env sh
IMG_NAME="base"
RELEASE=bullseye

ENABLE_SSH=1
PUBKEY_ONLY_SSH=0
TIMEZONE_DEFAULT=UTC

STAGE_LIST="stage0 stage1 stage2"

DEPLOY_COMPRESSION=none # disable output compression for the Packer ARM image plugin
