on: push
name: Build Image
env:
  generate-key: generate-arm64-${{ github.run_id }}
  build-key: build-arm64-${{ github.run_id }}
jobs:
  generate:
    name: Generate
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    defaults:
      run:
        working-directory: .
        shell: bash
    steps:
      - name: Checkout This Repository
        uses: actions/checkout@v3

      - name: Checkout Pi-Gen Repository
        uses: actions/checkout@v3
        with:
          path: .
          repository: RPi-Distro/pi-gen
          ref: arm64

      - name: List cwd
        run: ls -ah1

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          xargs sudo apt-get install -f <depends.txt

      - name: Make Image
        run: make

      - name: Setup Packer
        uses: hashicorp-contrib/setup-packer@v2

      - name: Pack Image
        run: |
          . config
          echo "$IMG_NAME"
          ISO_URL="./pi-gen/deploy/$IMG_NAME.img"
          ISO_CHECKSUM=$(cut -d' ' -f1 <"$ISO_URL".sha256)
          packer init ./packer
          packer build \
            -var source_iso_url="$ISO_URL" \
            -var source_iso_checksum="$ISO_CHECKSUM" \
            ./packer

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.generate-key}}
          path: |
            packer/*.img
            deploy/*.img
            deploy/*.sha256
