on: push
name: Build Image
jobs:
  build:
    name: Build
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    defaults:
      run:
        working-directory: .
        shell: bash
    steps:
      - name: Checkout This Repository
        uses: actions/checkout@v3

      - name: Checkout Pi-Gen Repository
        uses: actions/checkout@v3
        with:
          repository: RPi-Distro/pi-gen
          ref: arm64
          path: pi-gen

      - name: Setup Packer
        uses: hashicorp-contrib/setup-packer@v2

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          xargs sudo apt-get install -f <depends.txt

      - name: Move Build Files
        run: |
          mv config pi-gen/
          mv Makefile pi-gen/

      - name: Make Image
        run: |
          cd pi-gen
          make
          cd ..

      - name: Pack Image
        run: |
          cd packer
          packer init .
          echo "$IMG_NAME"
          packer build \
          -var source_iso_url=./pi-gen/deploy/"$IMG_NAME" \
          -var source_iso_checksum=$(cut -d' ' -f1 < ./pi-gen/deploy/"$IMG_NAME".sha256) \
          .

      - name: Upload Image
        uses: actions/upload-artifact@v3
        with:
          name: arm64-image-${{ github.run_id }}
          path: packer/*_arm64.img
