on: workflow_dispatch
name: Build Image
concurrency:
  group: build-{{ github.ref_name }}
  cancel-in-progress: true
env:
  image-key: image-arm64-${{ github.run_id }}
jobs:
  generate:
    name: Generate
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout This Repository
        uses: actions/checkout@v3

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          xargs sudo apt-get install -f <depends.txt

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.image-key }}
          path: |
            build/*.img
