on: push
name: Build Image
jobs:
  build:
    name: Build
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    defaults:
      run:
        working-directory: .
        shell: bash
    steps:
      - name: Checkout This Repository
        uses: actions/checkout@v3

      - name: Checkout Pi-Gen Repository
        uses: actions/checkout@v3
        with:
          path: pi-gen
          repository: RPi-Distro/pi-gen
          ref: arm64

      - name: Setup Packer
        uses: hashicorp-contrib/setup-packer@v2

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          xargs sudo apt-get install -f <depends.txt

      - name: Move Build Files
        run: |
          cp config pi-gen/
          mv Makefile pi-gen/

      - name: Make Image
        run: make
        working-directory: ./pi-gen

      - name: Pack Image
        run: |
          . config
          echo "$IMG_NAME"
          ISO_URL="./pi-gen/deploy/$IMG_NAME"
          ISO_CHECKSUM=$(cut -d' ' -f1 <"$ISO_URL".sha256)
          packer init ./packer
          packer build \
            -var source_iso_url="$ISO_URL" \
            -var source_iso_checksum="$ISO_CHECKSUM" \
            ./packer

      - name: Upload Image
        uses: actions/upload-artifact@v3
        with:
          name: arm64-image-${{ github.run_id }}
          path: packer/*_arm64.img
