on: push
name: Build Image
jobs:
  build:
    name: Build
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    defaults:
      run:
        working-directory: .
        shell: bash
    steps:
      - name: Checkout This Repository
        uses: actions/checkout@v3

      - name: Checkout Pi-Gen Repository
        uses: actions/checkout@v3
        with:
          repository: RPi-Distro/pi-gen
          ref: arm64
          path: pi-gen

      - name: Setup Packer
        uses: hashicorp-contrib/setup-packer@v2

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          xargs sudo apt-get install -f <depends.txt

      - name: Link Make Repository
        run: makepp -R pi-gen=. -F pi-gen

      - name: Make Images
        run: |
          cp config* pi-gen/
          cp Makefile pi-gen/
          mv packer/ pi-gen/
          cd pi-gen
          make images
