on: workflow_dispatch
name: Build Image
concurrency:
  group: build-{{ github.ref_name }}
  cancel-in-progress: true
env:
  image-key: image-arm64-${{ github.run_id }}
jobs:
  generate:
    name: Generate
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout This Repository
        uses: actions/checkout@v3

      - name: Checkout Pi-Gen Repository
        uses: actions/checkout@v3
        with:
          path: ./pi-gen
          repository: RPi-Distro/pi-gen
          ref: arm64

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          xargs sudo apt-get install -f <depends.txt

      - name: Make Image
        id: make_image
        working-directory: ./pi-gen
        run: |
          touch ./stage4/SKIP ./stage5/SKIP
          touch ./stage4/SKIP_IMAGES ./stage5/SKIP_IMAGES
          cp -R -f ../stage2 ./stage2
          cp -R -f ../stage3 ./stage3
          cp ../config .
          sudo ./build.sh
          echo "iso_url=$(ls -1 deploy/*.img | tail -n 1)" >>"$GITHUB_OUTPUT"
          ls -h1 deploy

      - name: Save SHA256 Checksum
        env:
          ISO_URL: ${{ steps.make_image.outputs.iso_url }}
        working-directory: ./pi-gen
        run: shasum -a 256 "$ISO_URL" | sudo tee "$ISO_URL.sha256"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.image-key }}
          path: |
            deploy/*.img
            deploy/*.info
            deploy/*.sha256
