on: push
name: Build Image
concurrency: build-{{ github.ref_name }}
env:
  generate-key: generate-arm64-${{ github.run_id }}
  build-key: build-arm64-${{ github.run_id }}
jobs:
  generate:
    name: Generate
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout This Repository
        uses: actions/checkout@v3

      - name: Checkout Pi-Gen Repository
        uses: actions/checkout@v3
        with:
          path: ./pi-gen
          repository: RPi-Distro/pi-gen
          ref: arm64

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          xargs sudo apt-get install -f <depends.txt

      - name: Make Image
        working-directory: ./pi-gen
        run: |
          touch ./stage3/SKIP ./stage4/SKIP ./stage5/SKIP
          touch ./stage4/SKIP_IMAGES ./stage5/SKIP_IMAGES
          cp -f ../EXPORT_IMAGE ./stage2/EXPORT_IMAGE
          cp ../config .
          sudo ./build.sh
          ls -ah1 deploy
          ls -ah1 deploy/*_arm64-lite/

      - name: Save SHA256 Checksum
        run: |
          . config
          ISO_URL="./pi-gen/deploy/$(date +%F)_$IMG_NAME.img"
          shasum -a 256 "$ISO_URL" | sudo tee "$ISO_URL.sha256"

      - name: Setup Packer
        uses: hashicorp-contrib/setup-packer@v2

      - name: Pack Image
        run: |
          . config
          echo "$IMG_NAME"
          ISO_URL="./pi-gen/deploy/$(date +%F)_$IMG_NAME.img"
          ISO_CHECKSUM=$(cut -d' ' -f1 <"$ISO_URL.sha256")
          packer init ./packer
          packer build \
            -var source_iso_url="$ISO_URL" \
            -var source_iso_checksum="$ISO_CHECKSUM" \
            ./packer

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.generate-key}}
          path: |
            packer/*.img
            deploy/*.img
            deploy/*.sha256
